# Generated by Django 6.0.1 on 2026-02-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('stop_requested', models.BooleanField(default=False)),
            ],
        ),
    ]
