# Generated by Django 6.0.1 on 2026-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_runcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('REPLIED', 'Replied'), ('ACKNOWLEDGED', 'Acknowledged'), ('NEEDS_REVIEW', 'Needs Review'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
