# Generated by Django 6.0.1 on 2026-02-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emaillog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='needs_manual_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('REPLIED', 'Replied (Auto)'), ('ACKNOWLEDGED', 'Acknowledged (Auto)'), ('NEEDS_REVIEW', 'Needs Manual Review'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
